#!/usr/bin/env python3
"""
build.py — Markdown to HTML pipeline for the mach-mono GitHub Pages site.

Reads:
 - <repo>/CHANGELOG.md       (Keep a Changelog format)
 - <repo>/Roadmap.md         (custom format with section icons and tags)
 - <repo>/Architecture.md     (architecture rationale and container diagram)

Renders:
  - <repo>/Apps/machNotch/updater/_template.html  (shared shell)

Writes:
  - <repo>/Apps/machNotch/updater/changelog.html
  - <repo>/Apps/machNotch/updater/roadmap.html
  - <repo>/Apps/machNotch/updater/diagram.html

Python 3 stdlib only. No pip, no external tools.

Usage (from any directory):
    python3 Apps/machNotch/updater/build.py
"""

from __future__ import annotations

import html
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent.parent
TEMPLATE_PATH = SCRIPT_DIR / "_template.html"
CHANGELOG_MD = REPO_ROOT / "CHANGELOG.md"
ROADMAP_MD = REPO_ROOT / "Roadmap.md"
DIAGRAM_MD = REPO_ROOT / "Architecture.md"
OVERVIEW_MD = REPO_ROOT / "Architecture.md"
CHANGELOG_OUT = SCRIPT_DIR / "changelog.html"
ROADMAP_OUT = SCRIPT_DIR / "roadmap.html"
DIAGRAM_OUT = SCRIPT_DIR / "diagram.html"

GENERATED_BANNER = (
    "<!-- generated by build.py — edit the source .md file instead -->"
)


# ---------------------------------------------------------------------------
# Nav
# ---------------------------------------------------------------------------

NAV_PAGES = [
    ("index.html",    "Home"),
    ("changelog.html", "Changelog"),
    ("roadmap.html",   "Roadmap"),
    ("diagram.html",   "Architecture"),
]


def render_nav_items(active_href: str) -> str:
    lines = []
    for href, label in NAV_PAGES:
        cls = ' class="active"' if href == active_href else ""
        lines.append(f'      <li><a href="{href}"{cls}>{label}</a></li>')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def slugify_version(version: str) -> str:
    slug = re.sub(r'[^\w]', '-', version.lower())
    return re.sub(r'-+', '-', slug).strip('-')


def strip_mermaid_fence(text: str) -> str:
    text = text.strip()
    if text.startswith("```mermaid"):
        text = text[len("```mermaid"):].strip()
    if text.endswith("```"):
        text = text[:-3].strip()
    return text


# ---------------------------------------------------------------------------
# Inline Markdown rendering
# ---------------------------------------------------------------------------

_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
_BOLD_RE = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC_RE = re.compile(r"(?<![\*_])\*([^*\n]+)\*(?![\*_])")
_CODE_RE = re.compile(r"`([^`]+)`")
_OL_ITEM_RE = re.compile(r"^\d+\.\s+(.+)$")


def render_inline(text: str) -> str:
    """Render inline Markdown to HTML."""
    code_spans: list[str] = []

    def _capture_code(m: re.Match[str]) -> str:
        code_spans.append(m.group(1))
        return f"\x00CODE{len(code_spans) - 1}\x00"

    work = _CODE_RE.sub(_capture_code, text)

    links: list[tuple[str, str]] = []

    def _capture_link(m: re.Match[str]) -> str:
        links.append((m.group(1), m.group(2)))
        return f"\x00LINK{len(links) - 1}\x00"

    work = _LINK_RE.sub(_capture_link, work)
    work = html.escape(work, quote=False)
    work = _BOLD_RE.sub(r"<strong>\1</strong>", work)
    work = _ITALIC_RE.sub(r"<em>\1</em>", work)

    def _restore_link(m: re.Match[str]) -> str:
        idx = int(m.group(1))
        label, href = links[idx]
        label_html = _BOLD_RE.sub(r"<strong>\1</strong>", html.escape(label, quote=False))
        label_html = _ITALIC_RE.sub(r"<em>\1</em>", label_html)
        return f'<a href="{html.escape(href, quote=True)}">{label_html}</a>'

    work = re.sub(r"\x00LINK(\d+)\x00", _restore_link, work)

    def _restore_code(m: re.Match[str]) -> str:
        idx = int(m.group(1))
        return f"<code>{html.escape(code_spans[idx], quote=False)}</code>"

    work = re.sub(r"\x00CODE(\d+)\x00", _restore_code, work)
    return work


# ---------------------------------------------------------------------------
# Block Markdown rendering
# ---------------------------------------------------------------------------

_TABLE_SEP_RE = re.compile(r"^:?-+:?$")


def render_table(lines: list[str]) -> str:
    """Render GFM table lines to HTML."""
    header_rows: list[list[str]] = []
    body_rows: list[list[str]] = []
    past_sep = False

    for line in lines:
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if all(_TABLE_SEP_RE.match(c) for c in cells if c):
            past_sep = True
        elif not past_sep:
            header_rows.append(cells)
        else:
            body_rows.append(cells)

    parts = ['<table class="adr-table">']
    if header_rows:
        parts.append(
            '<thead><tr>'
            + ''.join(f'<th>{render_inline(c)}</th>' for c in header_rows[0])
            + '</tr></thead>'
        )
    if body_rows:
        parts.append('<tbody>')
        for row in body_rows:
            parts.append(
                '<tr>'
                + ''.join(f'<td>{render_inline(c)}</td>' for c in row)
                + '</tr>'
            )
        parts.append('</tbody>')
    parts.append('</table>')
    return '\n'.join(parts)


def render_arch_table(lines: list[str]) -> str:
    """Render GFM table lines to HTML with arch-table class."""
    header_rows: list[list[str]] = []
    body_rows: list[list[str]] = []
    past_sep = False

    for line in lines:
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if all(_TABLE_SEP_RE.match(c) for c in cells if c):
            past_sep = True
        elif not past_sep:
            header_rows.append(cells)
        else:
            body_rows.append(cells)

    parts = ['<table class="arch-table">']
    if header_rows:
        parts.append(
            '<thead><tr>'
            + ''.join(f'<th>{render_inline(c)}</th>' for c in header_rows[0])
            + '</tr></thead>'
        )
    if body_rows:
        parts.append('<tbody>')
        for row in body_rows:
            parts.append(
                '<tr>'
                + ''.join(f'<td>{render_inline(c)}</td>' for c in row)
                + '</tr>'
            )
        parts.append('</tbody>')
    parts.append('</table>')
    return '\n'.join(parts)


def render_blocks(text: str) -> str:
    """Render block-level Markdown (paragraphs, lists, fenced code, tables)."""
    lines = text.splitlines()
    parts: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]

        # Fenced code block
        stripped = line.strip()
        if stripped.startswith("```"):
            lang = stripped[3:].strip()
            code_lines: list[str] = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i])
                i += 1
            i += 1  # skip closing fence
            code_content = html.escape("\n".join(code_lines))
            lang_cls = f' class="language-{html.escape(lang)}"' if lang else ''
            parts.append(f'<pre class="adr-pre"><code{lang_cls}>{code_content}</code></pre>')
            continue

        # Table
        if '|' in line and stripped.startswith('|'):
            table_lines: list[str] = []
            while i < len(lines) and '|' in lines[i] and lines[i].strip().startswith('|'):
                table_lines.append(lines[i])
                i += 1
            parts.append(render_table(table_lines))
            continue

        # List items
        if stripped.startswith('- ') or stripped.startswith('* '):
            list_items: list[str] = []
            while i < len(lines) and (
                lines[i].strip().startswith('- ') or lines[i].strip().startswith('* ')
            ):
                list_items.append(lines[i].strip()[2:])
                i += 1
            items_html = ''.join(f'<li>{render_inline(item)}</li>' for item in list_items)
            parts.append(f'<ul class="adr-list">{items_html}</ul>')
            continue

        # Blank line
        if not stripped:
            i += 1
            continue

        # Paragraph — collect until blank line or block element
        para_lines: list[str] = []
        while i < len(lines):
            stripped_line = lines[i].strip()
            if not stripped_line:
                break
            if stripped_line.startswith('```') or (stripped_line.startswith('|') and '|' in stripped_line) or stripped_line.startswith('- ') or stripped_line.startswith('* '):
                break
            para_lines.append(stripped_line)
            i += 1
        if para_lines:
            parts.append(f'<p class="adr-body">{render_inline(" ".join(para_lines))}</p>')

    return '\n'.join(parts)


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------

def _render_template(
    *,
    template_path: Path,
    title: str,
    page_style: str,
    active_href: str,
    content: str,
    og_title: str = "",
    og_description: str = "",
) -> str:
    template = template_path.read_text(encoding="utf-8")
    nav_items = render_nav_items(active_href)
    og_title = og_title or title
    return (
        template
        .replace("{{TITLE}}", title)
        .replace("{{OG_TITLE}}", html.escape(og_title, quote=True))
        .replace("{{OG_DESCRIPTION}}", html.escape(og_description, quote=True))
        .replace("{{PAGE_STYLE}}", page_style)
        .replace("{{NAV_ITEMS}}", nav_items)
        .replace("{{CONTENT}}", content)
    )


# ---------------------------------------------------------------------------
# Front matter
# ---------------------------------------------------------------------------

def strip_front_matter(text: str) -> tuple[dict[str, str], str]:
    meta: dict[str, str] = {}
    if not text.startswith("---"):
        return meta, text
    end = text.find("\n---", 3)
    if end == -1:
        return meta, text
    raw = text[3:end].strip("\n")
    body_start = text.find("\n", end + 4)
    body = text[body_start + 1:] if body_start != -1 else ""
    for line in raw.splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    return meta, body


# ---------------------------------------------------------------------------
# Changelog parsing
# ---------------------------------------------------------------------------

SECTION_DOT_RULES: list[tuple[tuple[str, ...], str]] = [
    (("bug", "fix"),                                           "#e05f6b"),
    (("new", "feat", "feature"),                               "#7c6ff7"),
    (("ui", "animation", "design", "polish"),                  "#5b8af7"),
    (("perf", "performance"),                                  "#d4a843"),
    (("arch", "solid", "ddd", "tech debt", "improvements", "hygiene"), "#e0874a"),
]


def dot_colour_for_section(title: str) -> str:
    lowered = title.lower()
    for keywords, colour in SECTION_DOT_RULES:
        for kw in keywords:
            if kw in lowered:
                return colour
    return "#6b6b8a"


@dataclass
class ChangeItem:
    name: str | None
    description: str


@dataclass
class ChangeSection:
    title: str
    items: list[ChangeItem] = field(default_factory=list)
    subsections: list[tuple[str, list[ChangeItem]]] = field(default_factory=list)
    intro: str = ""


@dataclass
class Release:
    version: str
    date: str | None
    released: bool
    sections: list[ChangeSection] = field(default_factory=list)
    intro: str = ""


_RELEASE_HEADING_RE = re.compile(r"^##\s+(?P<rest>.+?)\s*$")
_LIST_ITEM_RE = re.compile(r"^[\*\-]\s+(?P<body>.+)$")
_LEADER_RE = re.compile(r"^\*\*(?P<name>[^*]+)\*\*\s*[:\-—]\s*(?P<rest>.+)$")


def parse_release_heading(line: str) -> tuple[str, str | None] | None:
    m = _RELEASE_HEADING_RE.match(line)
    if not m:
        return None
    rest = m.group("rest").strip()
    date_match = re.search(r"(\d{4}-\d{2}-\d{2})", rest)
    if date_match:
        date = date_match.group(1)
        version = rest[: date_match.start()].strip(" —-").strip()
    else:
        date = None
        version = rest
    if version.startswith("[") and version.endswith("]"):
        version = version[1:-1]
    if not version:
        return None
    return version, date


def parse_changelog(md: str) -> list[Release]:
    releases: list[Release] = []
    current_release: Release | None = None
    current_section: ChangeSection | None = None
    current_subsection: tuple[str, list[ChangeItem]] | None = None

    lines = md.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()

        if line.startswith("## "):
            parsed = parse_release_heading(line)
            if parsed:
                version, date = parsed
                current_release = Release(version=version, date=date, released=date is not None)
                releases.append(current_release)
                current_section = None
                current_subsection = None
                i += 1
                continue
            current_section = None
            current_subsection = None
            i += 1
            continue

        if line.startswith("# "):
            i += 1
            continue

        if line.startswith("### "):
            if current_release is None:
                i += 1
                continue
            title = line[4:].strip()
            current_section = ChangeSection(title=title)
            current_release.sections.append(current_section)
            current_subsection = None
            i += 1
            continue

        if line.startswith("#### "):
            if current_section is None:
                i += 1
                continue
            sub_title = line[5:].strip()
            current_subsection = (sub_title, [])
            current_section.subsections.append(current_subsection)
            i += 1
            continue

        list_m = _LIST_ITEM_RE.match(line)
        if list_m and current_release is not None:
            body = list_m.group("body").strip()
            leader = _LEADER_RE.match(body)
            if leader:
                item = ChangeItem(name=leader.group("name").strip(), description=leader.group("rest").strip())
            else:
                item = ChangeItem(name=None, description=body)
            if current_subsection is not None:
                current_subsection[1].append(item)
            elif current_section is not None:
                current_section.items.append(item)
            i += 1
            continue

        if not line or line.strip() == "---":
            i += 1
            continue

        if current_release is not None:
            if current_section is not None:
                if not current_section.items:
                    existing = current_section.intro
                    current_section.intro = (existing + " " + line).strip() if existing else line
            else:
                existing = current_release.intro
                current_release.intro = (existing + " " + line).strip() if existing else line
        i += 1

    return releases


# ---------------------------------------------------------------------------
# Changelog HTML rendering
# ---------------------------------------------------------------------------

CHANGELOG_CSS = """
.release { width: 100%; max-width: 720px; margin-bottom: 48px; }

.release-header {
  display: flex;
  align-items: center;
  gap: 14px;
  margin-bottom: 28px;
}

.release-version {
  font-size: 20px;
  font-weight: 700;
  font-family: "SF Mono", "Fira Code", monospace;
  color: var(--text);
}

.release-version a {
  color: inherit;
  text-decoration: none;
}
.release-version a:hover { color: var(--accent); }

.release-badge {
  font-size: 11px;
  font-weight: 600;
  letter-spacing: .08em;
  padding: 3px 10px;
  border-radius: 20px;
}
.badge-unreleased { background: rgba(124,111,247,.18); color: var(--accent); }
.badge-released   { background: rgba(76,175,130,.15);  color: var(--green); }
.badge-latest     { background: rgba(76,175,130,.28);  color: var(--green); border: 1px solid rgba(76,175,130,.4); }

.release-date { font-size: 13px; color: var(--muted); margin-left: auto; }

.release-intro { font-size: 14px; color: var(--muted); line-height: 1.6; margin-bottom: 24px; }

.change-section { margin-bottom: 24px; }

.change-section-title {
  font-size: 12px;
  font-weight: 600;
  letter-spacing: .1em;
  text-transform: uppercase;
  color: var(--muted);
  margin-bottom: 12px;
  display: flex;
  align-items: center;
  gap: 8px;
}
.change-section-title::after { content: ''; flex: 1; height: 1px; background: var(--border); }

.dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; display: inline-block; }

.change-section-intro { font-size: 13px; color: var(--muted); line-height: 1.6; margin-bottom: 12px; }

.change-subsection-title {
  font-size: 12px;
  font-weight: 600;
  color: var(--text);
  margin: 16px 0 8px;
  letter-spacing: .02em;
}

.change-list { list-style: none; display: flex; flex-direction: column; gap: 8px; }

.change-item {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 12px 16px;
  font-size: 14px;
  line-height: 1.55;
  color: var(--muted);
}

.change-item strong { color: var(--text); font-weight: 600; }
.change-item code {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 12.5px;
  background: rgba(255,255,255,.05);
  padding: 1px 5px;
  border-radius: 4px;
  color: var(--text);
}
.change-item a { color: var(--accent); text-decoration: none; }
.change-item a:hover { text-decoration: underline; }
"""


def render_change_item(item: ChangeItem) -> str:
    if item.name:
        name_html = render_inline(item.name)
        desc_html = render_inline(item.description)
        return (
            f'      <li class="change-item">'
            f'<strong>{name_html}</strong>: {desc_html}'
            f'</li>'
        )
    desc_html = render_inline(item.description)
    return f'      <li class="change-item">{desc_html}</li>'


def render_change_section(section: ChangeSection) -> str:
    colour = dot_colour_for_section(section.title)
    parts: list[str] = []
    parts.append('  <div class="change-section">')
    parts.append(
        f'    <p class="change-section-title">'
        f'<span class="dot" style="background:{colour}"></span>'
        f'{html.escape(section.title)}</p>'
    )
    if section.intro:
        parts.append(f'    <p class="change-section-intro">{render_inline(section.intro)}</p>')
    if section.items:
        parts.append('    <ul class="change-list">')
        for item in section.items:
            parts.append(render_change_item(item))
        parts.append('    </ul>')
    for sub_title, sub_items in section.subsections:
        parts.append(f'    <p class="change-subsection-title">{html.escape(sub_title)}</p>')
        if sub_items:
            parts.append('    <ul class="change-list">')
            for item in sub_items:
                parts.append(render_change_item(item))
            parts.append('    </ul>')
    parts.append('  </div>')
    return "\n".join(parts)


def render_release(release: Release, *, is_latest: bool = False) -> str:
    anchor_id = slugify_version(release.version)
    badge_class = "badge-released" if release.released else "badge-unreleased"
    badge_label = "Released" if release.released else "Unreleased"

    parts: list[str] = []
    parts.append(f'<div class="release" id="v{anchor_id}">')
    parts.append('  <div class="release-header">')
    parts.append(
        f'    <span class="release-version">'
        f'<a href="#v{anchor_id}">{html.escape(release.version)}</a>'
        f'</span>'
    )
    parts.append(f'    <span class="release-badge {badge_class}">{badge_label}</span>')
    if is_latest:
        parts.append('    <span class="release-badge badge-latest">Latest</span>')
    if release.date:
        parts.append(f'    <span class="release-date">{html.escape(release.date)}</span>')
    parts.append('  </div>')
    if release.intro:
        parts.append(f'  <p class="release-intro">{render_inline(release.intro)}</p>')
    for section in release.sections:
        parts.append(render_change_section(section))
    parts.append('</div>')
    return "\n".join(parts)


def render_changelog_content(releases: list[Release]) -> str:
    # Find the first released entry for the "Latest" badge
    first_released_idx: int | None = None
    for idx, r in enumerate(releases):
        if r.released:
            first_released_idx = idx
            break

    parts: list[str] = []
    parts.append('<div class="page-header">')
    parts.append('  <h1>Changelog</h1>')
    parts.append(
        '  <p>What&#39;s new in mach.notch — every release, in order. '
        'For upcoming features see the <a href="roadmap.html">Roadmap</a>.</p>'
    )
    parts.append('</div>')
    for idx, release in enumerate(releases):
        parts.append(render_release(release, is_latest=(idx == first_released_idx)))
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Roadmap parsing & rendering
# ---------------------------------------------------------------------------

@dataclass
class RoadmapCard:
    title: str
    description: str
    tag: str | None


@dataclass
class RoadmapSection:
    icon: str
    title: str
    kind: str
    cards: list[RoadmapCard] = field(default_factory=list)
    empty_text: str | None = None


ICON_KIND = {
    "↑": "active",
    "⌛": "planned",
    "🚀": "launched",
}

_CARD_HEADING_RE = re.compile(r"^###\s+(?P<title>.+?)(?:\s+\[(?P<tag>[^\]]+)\])?\s*$")
_EMPTY_RE = re.compile(r"^_(.+)_\s*$")


def parse_section_heading(line: str) -> tuple[str, str, str] | None:
    if not line.startswith("## "):
        return None
    rest = line[3:].strip()
    parts = rest.split(None, 1)
    if len(parts) < 2:
        return None
    icon, title = parts[0], parts[1].strip()
    kind = ICON_KIND.get(icon, "other")
    return icon, title, kind


def parse_roadmap(md: str) -> tuple[str, list[RoadmapSection]]:
    meta, body = strip_front_matter(md)
    subtitle = meta.get("subtitle", "")
    sections: list[RoadmapSection] = []
    current_section: RoadmapSection | None = None
    current_card: RoadmapCard | None = None

    for raw_line in body.splitlines():
        line = raw_line.rstrip()
        sec = parse_section_heading(line)
        if sec is not None:
            icon, title, kind = sec
            current_section = RoadmapSection(icon=icon, title=title, kind=kind)
            sections.append(current_section)
            current_card = None
            continue
        card_m = _CARD_HEADING_RE.match(line)
        if card_m and current_section is not None:
            current_card = RoadmapCard(
                title=card_m.group("title").strip(),
                description="",
                tag=(card_m.group("tag") or "").strip() or None,
            )
            current_section.cards.append(current_card)
            continue
        if current_section is not None and not current_section.cards:
            empty_m = _EMPTY_RE.match(line.strip())
            if empty_m:
                current_section.empty_text = empty_m.group(1).strip()
                current_card = None
                continue
        if not line.strip():
            continue
        if current_card is not None:
            text = line.strip()
            current_card.description = (
                (current_card.description + " " + text).strip()
                if current_card.description
                else text
            )

    return subtitle, sections


ROADMAP_CSS = """
.rm-progress {
  width: 100%;
  max-width: 720px;
  margin-bottom: 48px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 16px 20px;
  display: flex;
  align-items: center;
  gap: 16px;
}
.rm-progress-track {
  flex: 1;
  height: 6px;
  background: var(--border);
  border-radius: 99px;
  overflow: hidden;
}
.rm-progress-fill {
  height: 100%;
  background: linear-gradient(90deg, var(--accent), var(--blue));
  border-radius: 99px;
  transition: width .4s ease;
}
.rm-progress-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--muted);
  white-space: nowrap;
}
.rm-progress-label strong { color: var(--green); }

.rm-section {
  width: 100%;
  max-width: 720px;
  display: grid;
  grid-template-columns: 160px 1fr;
  gap: 0 40px;
  margin-bottom: 56px;
}
.rm-section + .rm-section {
  padding-top: 48px;
  border-top: 1px solid var(--border);
}

.rm-label {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 8px;
  padding-top: 4px;
}
.rm-icon { font-size: 18px; line-height: 1; }
.rm-title {
  font-size: 20px;
  font-weight: 700;
  letter-spacing: -.02em;
  color: var(--text);
}
.rm-label.active .rm-title   { color: var(--green); }
.rm-label.planned .rm-title  { color: var(--orange); }
.rm-label.launched .rm-title { color: var(--blue); }

.rm-cards { display: flex; flex-direction: column; gap: 10px; }

.rm-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 16px 18px;
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
  transition: border-color .2s;
}
.rm-card:hover { border-color: #2e2e44; }

.rm-card-body { flex: 1; min-width: 0; }
.rm-card-title { font-size: 14px; font-weight: 600; color: var(--text); margin-bottom: 4px; }
.rm-card-desc  { font-size: 13px; color: var(--muted); line-height: 1.55; }

.rm-card-meta {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 6px;
  flex-shrink: 0;
}
.rm-tag {
  font-size: 11px;
  font-weight: 500;
  letter-spacing: .04em;
  color: var(--muted);
  background: rgba(255,255,255,.05);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 2px 8px;
}

.rm-empty {
  background: var(--surface);
  border: 1px dashed var(--border);
  border-radius: 10px;
  padding: 32px 24px;
  text-align: center;
  color: var(--muted);
  font-size: 13px;
  line-height: 1.6;
}

@media (max-width: 540px) {
  .rm-section { grid-template-columns: 1fr; gap: 20px 0; }
  .rm-label { flex-direction: row; align-items: center; }
}
"""


def render_roadmap_card(card: RoadmapCard) -> str:
    title_html = render_inline(card.title)
    desc_html = render_inline(card.description)
    meta_html = ""
    if card.tag:
        meta_html = (
            f'      <div class="rm-card-meta">'
            f'<span class="rm-tag">{html.escape(card.tag)}</span>'
            f'</div>'
        )
    parts = [
        '    <div class="rm-card">',
        '      <div class="rm-card-body">',
        f'        <div class="rm-card-title">{title_html}</div>',
        f'        <div class="rm-card-desc">{desc_html}</div>',
        '      </div>',
    ]
    if meta_html:
        parts.append(meta_html)
    parts.append('    </div>')
    return "\n".join(parts)


def render_roadmap_section(section: RoadmapSection) -> str:
    parts: list[str] = []
    parts.append('<div class="rm-section">')
    parts.append(f'  <div class="rm-label {section.kind}">')
    parts.append(f'    <span class="rm-icon">{html.escape(section.icon)}</span>')
    parts.append(f'    <span class="rm-title">{html.escape(section.title)}</span>')
    parts.append('  </div>')
    parts.append('  <div class="rm-cards">')
    if section.cards:
        for card in section.cards:
            parts.append(render_roadmap_card(card))
    elif section.empty_text:
        parts.append(f'    <div class="rm-empty">{render_inline(section.empty_text)}</div>')
    parts.append('  </div>')
    parts.append('</div>')
    return "\n".join(parts)


def render_roadmap_content(subtitle: str, sections: list[RoadmapSection]) -> str:
    total = launched = 0
    for s in sections:
        n = len(s.cards)
        total += n
        if s.kind == "launched":
            launched += n
    pct = round(launched / total * 100) if total else 0

    parts: list[str] = []
    parts.append('<div class="page-header">')
    parts.append('  <h1>Roadmap</h1>')
    if subtitle:
        parts.append(f'  <p>{render_inline(subtitle)}</p>')
    parts.append('</div>')

    # Progress strip
    parts.append('<div class="rm-progress">')
    parts.append('  <div class="rm-progress-track">')
    parts.append(f'    <div class="rm-progress-fill" style="width:{pct}%"></div>')
    parts.append('  </div>')
    parts.append(
        f'  <span class="rm-progress-label">'
        f'<strong>{launched}</strong> of {total} shipped'
        f'</span>'
    )
    parts.append('</div>')

    for section in sections:
        parts.append(render_roadmap_section(section))
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Architecture diagram page
# ---------------------------------------------------------------------------

DIAGRAM_CSS = """
.diagram-wrap {
  width: 100%;
  max-width: 720px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 16px;
  padding: 32px;
  margin-bottom: 48px;
  overflow-x: auto;
}
.diagram-wrap .mermaid { display: flex; justify-content: center; }
.diagram-wrap svg { max-width: 100%; height: auto; }
"""


ARCH_OVERVIEW_CSS = """
.arch-h2 {
  font-size: 17px;
  font-weight: 700;
  color: var(--text);
  margin: 48px 0 14px;
  letter-spacing: -.01em;
  display: flex;
  align-items: center;
  gap: 12px;
  max-width: 720px;
}
.arch-h2::after { content: ''; flex: 1; height: 1px; background: var(--border); }
.arch-h3 {
  font-size: 15px;
  font-weight: 600;
  color: var(--text);
  margin: 24px 0 10px;
  max-width: 720px;
}
.arch-h4 {
  font-size: 12px;
  font-weight: 600;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: .08em;
  margin: 20px 0 8px;
  max-width: 720px;
}
.arch-p {
  font-size: 14px;
  color: var(--muted);
  line-height: 1.65;
  margin-bottom: 12px;
  max-width: 720px;
}
.arch-note {
  max-width: 720px;
  background: rgba(124,111,247,.08);
  border-left: 3px solid var(--accent);
  border-radius: 0 8px 8px 0;
  padding: 12px 16px;
  margin-bottom: 16px;
  font-size: 13px;
  color: var(--muted);
  line-height: 1.6;
}
.arch-hr {
  border: none;
  border-top: 1px solid var(--border);
  max-width: 720px;
  margin: 32px 0;
}
.arch-table {
  width: 100%;
  max-width: 720px;
  border-collapse: collapse;
  font-size: 13px;
  margin-bottom: 16px;
}
.arch-table th, .arch-table td {
  text-align: left;
  padding: 8px 12px;
  border: 1px solid var(--border);
  color: var(--muted);
}
.arch-table th { color: var(--text); font-weight: 600; background: rgba(255,255,255,.03); }
.arch-list {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 6px;
  margin-bottom: 16px;
  max-width: 720px;
}
.arch-list li {
  font-size: 14px;
  color: var(--muted);
  line-height: 1.55;
  padding-left: 16px;
  position: relative;
}
.arch-list li::before { content: '–'; position: absolute; left: 0; color: var(--accent); }
.arch-ol {
  list-style: none;
  counter-reset: arch-counter;
  display: flex;
  flex-direction: column;
  gap: 6px;
  margin-bottom: 16px;
  max-width: 720px;
}
.arch-ol li {
  font-size: 14px;
  color: var(--muted);
  line-height: 1.55;
  padding-left: 24px;
  position: relative;
  counter-increment: arch-counter;
}
.arch-ol li::before {
  content: counter(arch-counter) '.';
  position: absolute;
  left: 0;
  color: var(--accent);
  font-weight: 600;
}
.arch-pre {
  max-width: 720px;
  background: rgba(0,0,0,.3);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 14px 16px;
  overflow-x: auto;
  margin-bottom: 16px;
}
.arch-pre code {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 12px;
  color: var(--text);
  white-space: pre;
}
.arch-p code, .arch-h3 code, .arch-list li code, .arch-ol li code, .arch-note code {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 12px;
  background: rgba(255,255,255,.05);
  padding: 1px 5px;
  border-radius: 4px;
  color: var(--text);
}
"""


def render_overview_blocks(text: str) -> str:
    """Render overview.md to HTML: headings, mermaid, tables, code, lists, blockquotes."""
    lines = text.splitlines()
    parts: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Skip H1 — page header already provides the title
        if stripped.startswith('# ') and not stripped.startswith('## '):
            i += 1
            continue

        # H2
        if stripped.startswith('## ') and not stripped.startswith('### '):
            parts.append(f'<h2 class="arch-h2">{render_inline(stripped[3:].strip())}</h2>')
            i += 1
            continue

        # H3
        if stripped.startswith('### ') and not stripped.startswith('#### '):
            parts.append(f'<h3 class="arch-h3">{render_inline(stripped[4:].strip())}</h3>')
            i += 1
            continue

        # H4
        if stripped.startswith('#### '):
            parts.append(f'<h4 class="arch-h4">{render_inline(stripped[5:].strip())}</h4>')
            i += 1
            continue

        # HR
        if stripped == '---':
            parts.append('<hr class="arch-hr">')
            i += 1
            continue

        # Fenced code block (mermaid rendered inline; others as <pre>)
        if stripped.startswith('```'):
            lang = stripped[3:].strip()
            code_lines: list[str] = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith('```'):
                code_lines.append(lines[i])
                i += 1
            i += 1  # skip closing fence
            if lang == 'mermaid':
                escaped = html.escape('\n'.join(code_lines))
                parts.append('<div class="diagram-wrap">')
                parts.append(f'  <div class="mermaid">{escaped}</div>')
                parts.append('</div>')
            else:
                code_content = html.escape('\n'.join(code_lines))
                lang_cls = f' class="language-{html.escape(lang)}"' if lang else ''
                parts.append(f'<pre class="arch-pre"><code{lang_cls}>{code_content}</code></pre>')
            continue

        # Blockquote
        if stripped.startswith('> '):
            bq_lines: list[str] = []
            while i < len(lines) and lines[i].strip().startswith('> '):
                bq_lines.append(lines[i].strip()[2:])
                i += 1
            parts.append(f'<div class="arch-note">{render_inline(" ".join(bq_lines))}</div>')
            continue

        # Table
        if '|' in line and stripped.startswith('|'):
            table_lines: list[str] = []
            while i < len(lines) and '|' in lines[i] and lines[i].strip().startswith('|'):
                table_lines.append(lines[i])
                i += 1
            parts.append(render_arch_table(table_lines))
            continue

        # Unordered list (handles both `- ` and `* ` prefixes)
        if stripped.startswith('- ') or stripped.startswith('* '):
            list_items: list[str] = []
            while i < len(lines) and (
                lines[i].strip().startswith('- ') or lines[i].strip().startswith('* ')
            ):
                list_items.append(lines[i].strip()[2:].strip())
                i += 1
            items_html = ''.join(f'<li>{render_inline(item)}</li>' for item in list_items)
            parts.append(f'<ul class="arch-list">{items_html}</ul>')
            continue

        # Ordered list
        if _OL_ITEM_RE.match(stripped):
            ol_items: list[str] = []
            while i < len(lines):
                m = _OL_ITEM_RE.match(lines[i].strip())
                if not m:
                    break
                ol_items.append(m.group(1))
                i += 1
            items_html = ''.join(f'<li>{render_inline(item)}</li>' for item in ol_items)
            parts.append(f'<ol class="arch-ol">{items_html}</ol>')
            continue

        # Blank line
        if not stripped:
            i += 1
            continue

        # Paragraph — collect until a block-level element or blank line
        para_lines: list[str] = []
        while i < len(lines):
            sl = lines[i].strip()
            if not sl:
                break
            if (sl.startswith('```') or sl.startswith('## ') or sl.startswith('### ')
                    or sl.startswith('#### ') or sl.startswith('# ')
                    or (sl.startswith('|') and '|' in sl)
                    or sl.startswith('- ') or sl.startswith('* ')
                    or _OL_ITEM_RE.match(sl)
                    or sl.startswith('> ')
                    or sl == '---'):
                break
            para_lines.append(sl)
            i += 1
        if para_lines:
            parts.append(f'<p class="arch-p">{render_inline(" ".join(para_lines))}</p>')

    return '\n'.join(parts)


def render_diagram_content(mermaid_source: str, overview_text: str = "") -> str:
    diagram_html = html.escape(mermaid_source)
    parts: list[str] = []
    parts.append('<div class="page-header">')
    parts.append('  <h1>Architecture</h1>')
    parts.append(
        '  <p>High-level structure of the mach-mono monorepo — build orchestration, '
        'apps, and shared packages.</p>'
    )
    parts.append('</div>')
    parts.append('<div class="diagram-wrap">')
    parts.append(f'  <div class="mermaid">{diagram_html}</div>')
    parts.append('</div>')
    if overview_text:
        parts.append(render_overview_blocks(overview_text))
    # Mermaid.js initialisation — loaded from CDN, after all .mermaid divs are in the DOM
    parts.append(
        '<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>'
    )
    parts.append(
        '<script>'
        'mermaid.initialize({'
        'startOnLoad:true,'
        'theme:"dark",'
        'themeVariables:{'
        'background:"#13131f",'
        'primaryColor:"#1e1e2e",'
        'primaryTextColor:"#e2e2f0",'
        'lineColor:"#6b6b8a",'
        'edgeLabelBackground:"#13131f"'
        '}'
        '});'
        '</script>'
    )
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Build entry points
# ---------------------------------------------------------------------------

def build_changelog(*, changelog_path: Path, template_path: Path, out_path: Path) -> None:
    md = changelog_path.read_text(encoding="utf-8")
    releases = parse_changelog(md)
    if not releases:
        print(f"warning: no releases parsed from {changelog_path}", file=sys.stderr)
    content = render_changelog_content(releases)
    rendered = _render_template(
        template_path=template_path,
        title="Changelog — mach",
        page_style=CHANGELOG_CSS,
        active_href="changelog.html",
        content=content,
        og_description="What's new in mach.notch — every release, in order.",
    )
    out_path.write_text(GENERATED_BANNER + "\n" + rendered, encoding="utf-8")
    print(f"wrote {out_path} ({len(releases)} releases)")


def build_roadmap(*, roadmap_path: Path, template_path: Path, out_path: Path) -> None:
    md = roadmap_path.read_text(encoding="utf-8")
    subtitle, sections = parse_roadmap(md)
    content = render_roadmap_content(subtitle, sections)
    rendered = _render_template(
        template_path=template_path,
        title="Roadmap — mach",
        page_style=ROADMAP_CSS,
        active_href="roadmap.html",
        content=content,
        og_description="What's being built, what's next, and what has shipped in mach-mono.",
    )
    out_path.write_text(GENERATED_BANNER + "\n" + rendered, encoding="utf-8")
    card_count = sum(len(s.cards) for s in sections)
    print(f"wrote {out_path} ({len(sections)} sections, {card_count} cards)")


def build_diagram(*, diagram_path: Path, overview_path: Path | None, template_path: Path, out_path: Path) -> None:
    raw = diagram_path.read_text(encoding="utf-8")
    if diagram_path.suffix.lower() == ".md":
        match = re.search(r"###\s+Container Diagram.*?\n```mermaid\n(.*?)\n```", raw, re.DOTALL | re.IGNORECASE)
        if match:
            mermaid_source = match.group(1).strip()
        else:
            match_first = re.search(r"```mermaid\n(.*?)\n```", raw, re.DOTALL | re.IGNORECASE)
            if match_first:
                mermaid_source = match_first.group(1).strip()
            else:
                print(f"error: no mermaid block found in {diagram_path}", file=sys.stderr)
                mermaid_source = ""
    else:
        mermaid_source = strip_mermaid_fence(raw)
    overview_text = overview_path.read_text(encoding="utf-8") if overview_path and overview_path.is_file() else ""
    content = render_diagram_content(mermaid_source, overview_text)
    rendered = _render_template(
        template_path=template_path,
        title="Architecture — mach",
        page_style=DIAGRAM_CSS + ARCH_OVERVIEW_CSS,
        active_href="diagram.html",
        content=content,
        og_description="High-level architecture of the mach-mono monorepo.",
    )
    out_path.write_text(GENERATED_BANNER + "\n" + rendered, encoding="utf-8")
    print(f"wrote {out_path}")


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Build mach-mono GitHub Pages from Markdown sources."
    )
    parser.add_argument("--changelog",  type=Path, default=CHANGELOG_MD)
    parser.add_argument("--roadmap",    type=Path, default=ROADMAP_MD)
    parser.add_argument("--diagram",    type=Path, default=DIAGRAM_MD)
    parser.add_argument("--overview",   type=Path, default=OVERVIEW_MD)
    parser.add_argument("--template",   type=Path, default=TEMPLATE_PATH)
    parser.add_argument("--outdir",     type=Path, default=SCRIPT_DIR)
    args = parser.parse_args(argv)

    for label, path in [
        ("template",  args.template),
        ("changelog", args.changelog),
        ("roadmap",   args.roadmap),
        ("diagram",   args.diagram),
    ]:
        if not path.is_file():
            print(f"error: {label} not found at {path}", file=sys.stderr)
            return 1

    overview_path: Path | None = args.overview if args.overview.is_file() else None
    if overview_path is None:
        print(f"warning: overview not found at {args.overview}, skipping", file=sys.stderr)

    args.outdir.mkdir(parents=True, exist_ok=True)

    build_changelog(changelog_path=args.changelog, template_path=args.template,
                    out_path=args.outdir / "changelog.html")
    build_roadmap(roadmap_path=args.roadmap, template_path=args.template,
                  out_path=args.outdir / "roadmap.html")
    build_diagram(diagram_path=args.diagram, overview_path=overview_path,
                  template_path=args.template, out_path=args.outdir / "diagram.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
