genrule(
    name = "site",
    srcs = [
        "//:CHANGELOG.md",
        "//:ROADMAP.md",
        "_template.html",
        "build.py",
    ],
    outs = [
        "changelog.html",
        "roadmap.html",
    ],
    cmd = " ".join([
        "python3 $(location build.py)",
        "--changelog $(location //:CHANGELOG.md)",
        "--roadmap   $(location //:ROADMAP.md)",
        "--template  $(location _template.html)",
        "--outdir    $(@D)",
    ]),
)
