#!/usr/bin/env python3
"""
build.py — Markdown to HTML pipeline for the mach-mono GitHub Pages site.

Reads:
  - <repo>/CHANGELOG.md       (Keep a Changelog format)
  - <repo>/ROADMAP.md         (custom format with section icons and tags)

Renders:
  - <repo>/Apps/machNotch/updater/_template.html  (shared shell)

Writes:
  - <repo>/Apps/machNotch/updater/changelog.html
  - <repo>/Apps/machNotch/updater/roadmap.html

Python 3 stdlib only. No pip, no external tools.

Usage (from any directory):
    python3 Apps/machNotch/updater/build.py
"""

from __future__ import annotations

import html
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


# ---------------------------------------------------------------------------
# Paths (resolved relative to this file, so the script is location-independent)
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent           # .../Apps/machNotch/updater
REPO_ROOT = SCRIPT_DIR.parent.parent.parent            # repo root
TEMPLATE_PATH = SCRIPT_DIR / "_template.html"
CHANGELOG_MD = REPO_ROOT / "CHANGELOG.md"
ROADMAP_MD = REPO_ROOT / "ROADMAP.md"
CHANGELOG_OUT = SCRIPT_DIR / "changelog.html"
ROADMAP_OUT = SCRIPT_DIR / "roadmap.html"

GENERATED_BANNER = (
    "<!-- generated by build.py — edit CHANGELOG.md or ROADMAP.md instead -->"
)


# ---------------------------------------------------------------------------
# Nav rendering
# ---------------------------------------------------------------------------

NAV_PAGES = [
    ("index.html", "Home"),
    ("changelog.html", "Changelog"),
    ("roadmap.html", "Roadmap"),
    ("guide.html", "Guide"),
]


def render_nav_items(active_href: str) -> str:
    lines = []
    for href, label in NAV_PAGES:
        cls = ' class="active"' if href == active_href else ""
        lines.append(f'      <li><a href="{href}"{cls}>{label}</a></li>')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Inline Markdown rendering
# ---------------------------------------------------------------------------

# Order matters: code first (it suppresses other interpretation), then links,
# then bold, then italic.
_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
_BOLD_RE = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC_RE = re.compile(r"(?<![\*_])\*([^*\n]+)\*(?![\*_])")
_CODE_RE = re.compile(r"`([^`]+)`")


def render_inline(text: str) -> str:
    """Render inline Markdown to HTML, escaping everything else."""
    # 1. Pull out backtick-code spans first; replace with sentinels so their
    #    contents are escaped but never re-interpreted.
    code_spans: list[str] = []

    def _capture_code(m: re.Match[str]) -> str:
        code_spans.append(m.group(1))
        return f"\x00CODE{len(code_spans) - 1}\x00"

    work = _CODE_RE.sub(_capture_code, text)

    # 2. Pull out link spans the same way (text + href captured raw).
    links: list[tuple[str, str]] = []

    def _capture_link(m: re.Match[str]) -> str:
        links.append((m.group(1), m.group(2)))
        return f"\x00LINK{len(links) - 1}\x00"

    work = _LINK_RE.sub(_capture_link, work)

    # 3. HTML-escape the surviving plain text.
    work = html.escape(work, quote=False)

    # 4. Render bold + italic on the escaped text (safe — markers are ASCII).
    work = _BOLD_RE.sub(r"<strong>\1</strong>", work)
    work = _ITALIC_RE.sub(r"<em>\1</em>", work)

    # 5. Restore link sentinels with escaped href/text.
    def _restore_link(m: re.Match[str]) -> str:
        idx = int(m.group(1))
        label, href = links[idx]
        # label might itself contain bold/italic — render recursively but
        # without re-entering code/link capture.
        label_html = _BOLD_RE.sub(
            r"<strong>\1</strong>",
            html.escape(label, quote=False),
        )
        label_html = _ITALIC_RE.sub(r"<em>\1</em>", label_html)
        return f'<a href="{html.escape(href, quote=True)}">{label_html}</a>'

    work = re.sub(r"\x00LINK(\d+)\x00", _restore_link, work)

    # 6. Restore code spans (escape contents, no further interpretation).
    def _restore_code(m: re.Match[str]) -> str:
        idx = int(m.group(1))
        return f"<code>{html.escape(code_spans[idx], quote=False)}</code>"

    work = re.sub(r"\x00CODE(\d+)\x00", _restore_code, work)

    return work


# ---------------------------------------------------------------------------
# Template loading
# ---------------------------------------------------------------------------

def load_template() -> str:
    return TEMPLATE_PATH.read_text(encoding="utf-8")


def render_template(
    *,
    title: str,
    page_style: str,
    active_href: str,
    content: str,
) -> str:
    template = load_template()
    nav_items = render_nav_items(active_href)
    return (
        template
        .replace("{{TITLE}}", title)
        .replace("{{PAGE_STYLE}}", page_style)
        .replace("{{NAV_ITEMS}}", nav_items)
        .replace("{{CONTENT}}", content)
    )


# ---------------------------------------------------------------------------
# Front matter (used by ROADMAP.md)
# ---------------------------------------------------------------------------

def strip_front_matter(text: str) -> tuple[dict[str, str], str]:
    """Parse simple key: value YAML-ish front matter delimited by `---`."""
    meta: dict[str, str] = {}
    if not text.startswith("---"):
        return meta, text
    end = text.find("\n---", 3)
    if end == -1:
        return meta, text
    raw = text[3:end].strip("\n")
    body_start = text.find("\n", end + 4)
    body = text[body_start + 1:] if body_start != -1 else ""
    for line in raw.splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    return meta, body


# ---------------------------------------------------------------------------
# Changelog parsing
# ---------------------------------------------------------------------------

# Section keyword -> (dot colour, badge label or None)
# We only need the dot colour; section title text comes from the heading as-is.
SECTION_DOT_RULES: list[tuple[tuple[str, ...], str]] = [
    # bug/fix family
    (("bug", "fix"), "#e05f6b"),
    # new/feat family
    (("new", "feat", "feature"), "#7c6ff7"),
    # ui/animation family
    (("ui", "animation", "design", "polish"), "#5b8af7"),
    # perf family
    (("perf", "performance"), "#d4a843"),
    # arch / solid / ddd family
    (("arch", "solid", "ddd", "tech debt", "improvements", "hygiene"), "#e0874a"),
]


def dot_colour_for_section(title: str) -> str:
    lowered = title.lower()
    for keywords, colour in SECTION_DOT_RULES:
        for kw in keywords:
            if kw in lowered:
                return colour
    return "#6b6b8a"  # var(--muted)


@dataclass
class ChangeItem:
    name: str | None   # bolded leader (e.g. "Bazel CI")
    description: str   # remainder; may be empty


@dataclass
class ChangeSection:
    title: str         # raw heading text (with emoji prefix kept)
    items: list[ChangeItem] = field(default_factory=list)
    subsections: list[tuple[str, list[ChangeItem]]] = field(default_factory=list)
    intro: str = ""    # plain paragraph text appearing before any item


@dataclass
class Release:
    version: str       # e.g. "Pre-release" or "[0.1.0]"
    date: str | None   # "2026-01-01" or None
    released: bool     # True if a date is present
    sections: list[ChangeSection] = field(default_factory=list)
    intro: str = ""    # plain paragraph below the H2 (before any H3)


_RELEASE_HEADING_RE = re.compile(
    r"^##\s+(?P<rest>.+?)\s*$"
)
# Match `- **Name**: desc` or `*   **Name**: desc` or bare `- desc`.
_LIST_ITEM_RE = re.compile(r"^[\*\-]\s+(?P<body>.+)$")
_LEADER_RE = re.compile(r"^\*\*(?P<name>[^*]+)\*\*\s*[:\-—]\s*(?P<rest>.+)$")


def parse_release_heading(line: str) -> tuple[str, str | None] | None:
    """
    Return (version, date) for release H2 lines, or None if not a release.

    Accepts:
        ## Pre-release
        ## [0.1.0] — 2026-01-01
        ## [0.1.0] - 2026-01-01
        ## 0.1.0 - 2026-01-01
    Skips:
        ## anything else (e.g. ## Releases header)
    """
    m = _RELEASE_HEADING_RE.match(line)
    if not m:
        return None
    rest = m.group("rest").strip()

    # Plain "Pre-release" (or any text without a date) — accept as unreleased.
    # Heuristic: look for an ISO date.
    date_match = re.search(r"(\d{4}-\d{2}-\d{2})", rest)
    if date_match:
        date = date_match.group(1)
        version = rest[: date_match.start()].strip(" —-").strip()
    else:
        date = None
        version = rest

    # Strip surrounding [] off version
    if version.startswith("[") and version.endswith("]"):
        version = version[1:-1]

    if not version:
        return None
    return version, date


def parse_changelog(md: str) -> list[Release]:
    """Parse the Keep a Changelog file into Release objects."""
    releases: list[Release] = []
    current_release: Release | None = None
    current_section: ChangeSection | None = None
    current_subsection: tuple[str, list[ChangeItem]] | None = None

    lines = md.splitlines()
    i = 0
    in_intro_paragraph = False  # tracks whether we're collecting prose
    while i < len(lines):
        line = lines[i].rstrip()

        # H2 release heading
        if line.startswith("## "):
            parsed = parse_release_heading(line)
            if parsed:
                version, date = parsed
                current_release = Release(
                    version=version,
                    date=date,
                    released=date is not None,
                )
                releases.append(current_release)
                current_section = None
                current_subsection = None
                in_intro_paragraph = False
                i += 1
                continue
            # Non-release H2 (e.g. "# Changelog" preamble already skipped at H1).
            # Treat as a paragraph break and ignore.
            current_section = None
            current_subsection = None
            in_intro_paragraph = False
            i += 1
            continue

        # H1 — ignore (document title)
        if line.startswith("# "):
            i += 1
            continue

        # H3 section
        if line.startswith("### "):
            if current_release is None:
                i += 1
                continue
            title = line[4:].strip()
            current_section = ChangeSection(title=title)
            current_release.sections.append(current_section)
            current_subsection = None
            in_intro_paragraph = False
            i += 1
            continue

        # H4 subsection
        if line.startswith("#### "):
            if current_section is None:
                i += 1
                continue
            sub_title = line[5:].strip()
            current_subsection = (sub_title, [])
            current_section.subsections.append(current_subsection)
            in_intro_paragraph = False
            i += 1
            continue

        # List item
        list_m = _LIST_ITEM_RE.match(line)
        if list_m and current_release is not None:
            body = list_m.group("body").strip()
            leader = _LEADER_RE.match(body)
            if leader:
                item = ChangeItem(
                    name=leader.group("name").strip(),
                    description=leader.group("rest").strip(),
                )
            else:
                item = ChangeItem(name=None, description=body)
            if current_subsection is not None:
                current_subsection[1].append(item)
            elif current_section is not None:
                current_section.items.append(item)
            # Items outside any section are dropped intentionally.
            in_intro_paragraph = False
            i += 1
            continue

        # Horizontal rule / blank — paragraph break
        if not line or line.strip() == "---":
            in_intro_paragraph = False
            i += 1
            continue

        # Plain paragraph text
        if current_release is not None:
            target_attr = None
            if current_section is not None:
                target_attr = "intro" if not current_section.items else None
                if target_attr:
                    existing = current_section.intro
                    current_section.intro = (
                        (existing + " " + line).strip() if existing else line
                    )
                # Else: ignore prose interleaved between items.
            else:
                # Release-level intro (between H2 and first H3)
                existing = current_release.intro
                current_release.intro = (
                    (existing + " " + line).strip() if existing else line
                )
            in_intro_paragraph = True
        i += 1

    return releases


# ---------------------------------------------------------------------------
# Changelog HTML rendering
# ---------------------------------------------------------------------------

CHANGELOG_CSS = """
.release { width: 100%; max-width: 720px; margin-bottom: 48px; }

.release-header {
  display: flex;
  align-items: center;
  gap: 14px;
  margin-bottom: 28px;
}

.release-version {
  font-size: 20px;
  font-weight: 700;
  font-family: "SF Mono", "Fira Code", monospace;
  color: var(--text);
}

.release-badge {
  font-size: 11px;
  font-weight: 600;
  letter-spacing: .08em;
  padding: 3px 10px;
  border-radius: 20px;
}
.badge-unreleased { background: rgba(124,111,247,.18); color: var(--accent); }
.badge-released   { background: rgba(76,175,130,.15);  color: var(--green); }

.release-date { font-size: 13px; color: var(--muted); margin-left: auto; }

.release-intro { font-size: 14px; color: var(--muted); line-height: 1.6; margin-bottom: 24px; }

.change-section { margin-bottom: 24px; }

.change-section-title {
  font-size: 12px;
  font-weight: 600;
  letter-spacing: .1em;
  text-transform: uppercase;
  color: var(--muted);
  margin-bottom: 12px;
  display: flex;
  align-items: center;
  gap: 8px;
}
.change-section-title::after { content: ''; flex: 1; height: 1px; background: var(--border); }

.dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; display: inline-block; }

.change-section-intro { font-size: 13px; color: var(--muted); line-height: 1.6; margin-bottom: 12px; }

.change-subsection-title {
  font-size: 12px;
  font-weight: 600;
  color: var(--text);
  margin: 16px 0 8px;
  letter-spacing: .02em;
}

.change-list { list-style: none; display: flex; flex-direction: column; gap: 8px; }

.change-item {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 12px 16px;
  font-size: 14px;
  line-height: 1.55;
  color: var(--muted);
}

.change-item strong { color: var(--text); font-weight: 600; }
.change-item code {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 12.5px;
  background: rgba(255,255,255,.05);
  padding: 1px 5px;
  border-radius: 4px;
  color: var(--text);
}
.change-item a { color: var(--accent); text-decoration: none; }
.change-item a:hover { text-decoration: underline; }
"""


def render_change_item(item: ChangeItem) -> str:
    if item.name:
        name_html = render_inline(item.name)
        desc_html = render_inline(item.description)
        return (
            f'      <li class="change-item">'
            f'<strong>{name_html}</strong>: {desc_html}'
            f'</li>'
        )
    desc_html = render_inline(item.description)
    return f'      <li class="change-item">{desc_html}</li>'


def render_change_section(section: ChangeSection) -> str:
    colour = dot_colour_for_section(section.title)
    parts: list[str] = []
    parts.append('  <div class="change-section">')
    parts.append(
        f'    <p class="change-section-title">'
        f'<span class="dot" style="background:{colour}"></span>'
        f'{html.escape(section.title)}</p>'
    )
    if section.intro:
        parts.append(
            f'    <p class="change-section-intro">{render_inline(section.intro)}</p>'
        )
    if section.items:
        parts.append('    <ul class="change-list">')
        for item in section.items:
            parts.append(render_change_item(item))
        parts.append('    </ul>')

    for sub_title, sub_items in section.subsections:
        parts.append(
            f'    <p class="change-subsection-title">{html.escape(sub_title)}</p>'
        )
        if sub_items:
            parts.append('    <ul class="change-list">')
            for item in sub_items:
                parts.append(render_change_item(item))
            parts.append('    </ul>')

    parts.append('  </div>')
    return "\n".join(parts)


def render_release(release: Release) -> str:
    badge_class = "badge-released" if release.released else "badge-unreleased"
    badge_label = "Released" if release.released else "Unreleased"

    parts: list[str] = []
    parts.append('<div class="release">')
    parts.append('  <div class="release-header">')
    parts.append(
        f'    <span class="release-version">{html.escape(release.version)}</span>'
    )
    parts.append(
        f'    <span class="release-badge {badge_class}">{badge_label}</span>'
    )
    if release.date:
        parts.append(
            f'    <span class="release-date">{html.escape(release.date)}</span>'
        )
    parts.append('  </div>')

    if release.intro:
        parts.append(
            f'  <p class="release-intro">{render_inline(release.intro)}</p>'
        )

    for section in release.sections:
        parts.append(render_change_section(section))

    parts.append('</div>')
    return "\n".join(parts)


def render_changelog_content(releases: list[Release]) -> str:
    parts: list[str] = []
    parts.append('<div class="page-header">')
    parts.append('  <h1>Changelog</h1>')
    parts.append(
        '  <p>What&#39;s new in mach.notch — every release, in order. '
        'For upcoming features see the <a href="roadmap.html">Roadmap</a>.</p>'
    )
    parts.append('</div>')
    for release in releases:
        parts.append(render_release(release))
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Roadmap parsing & rendering
# ---------------------------------------------------------------------------

@dataclass
class RoadmapCard:
    title: str
    description: str
    tag: str | None


@dataclass
class RoadmapSection:
    icon: str
    title: str
    kind: str           # "active" | "planned" | "launched" | "other"
    cards: list[RoadmapCard] = field(default_factory=list)
    empty_text: str | None = None


ICON_KIND = {
    "↑": "active",
    "⌛": "planned",
    "🚀": "launched",
}

# Card heading: `### Card Title [Tag]` (tag optional)
_CARD_HEADING_RE = re.compile(r"^###\s+(?P<title>.+?)(?:\s+\[(?P<tag>[^\]]+)\])?\s*$")
# Empty-state italic line: `_text_`
_EMPTY_RE = re.compile(r"^_(.+)_\s*$")


def parse_section_heading(line: str) -> tuple[str, str, str] | None:
    """Return (icon, title, kind) for an H2 roadmap heading."""
    if not line.startswith("## "):
        return None
    rest = line[3:].strip()
    # First "character" might be a multi-codepoint emoji; split on first space.
    parts = rest.split(None, 1)
    if len(parts) < 2:
        return None
    icon, title = parts[0], parts[1].strip()
    kind = ICON_KIND.get(icon, "other")
    return icon, title, kind


def parse_roadmap(md: str) -> tuple[str, list[RoadmapSection]]:
    """Parse ROADMAP.md and return (subtitle, sections)."""
    meta, body = strip_front_matter(md)
    subtitle = meta.get("subtitle", "")

    sections: list[RoadmapSection] = []
    current_section: RoadmapSection | None = None
    current_card: RoadmapCard | None = None

    for raw_line in body.splitlines():
        line = raw_line.rstrip()

        # H2 — new section
        sec = parse_section_heading(line)
        if sec is not None:
            icon, title, kind = sec
            current_section = RoadmapSection(icon=icon, title=title, kind=kind)
            sections.append(current_section)
            current_card = None
            continue

        # H3 — new card
        card_m = _CARD_HEADING_RE.match(line)
        if card_m and current_section is not None:
            current_card = RoadmapCard(
                title=card_m.group("title").strip(),
                description="",
                tag=(card_m.group("tag") or "").strip() or None,
            )
            current_section.cards.append(current_card)
            continue

        # Italic-only line — empty state for the section
        if current_section is not None and not current_section.cards:
            empty_m = _EMPTY_RE.match(line.strip())
            if empty_m:
                current_section.empty_text = empty_m.group(1).strip()
                current_card = None
                continue

        # Blank line
        if not line.strip():
            continue

        # Continuation paragraph text on the current card
        if current_card is not None:
            text = line.strip()
            current_card.description = (
                (current_card.description + " " + text).strip()
                if current_card.description
                else text
            )

    return subtitle, sections


ROADMAP_CSS = """
.rm-section {
  width: 100%;
  max-width: 720px;
  display: grid;
  grid-template-columns: 160px 1fr;
  gap: 0 40px;
  margin-bottom: 56px;
}
.rm-section + .rm-section {
  padding-top: 48px;
  border-top: 1px solid var(--border);
}

.rm-label {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 8px;
  padding-top: 4px;
}
.rm-icon { font-size: 18px; line-height: 1; }
.rm-title {
  font-size: 20px;
  font-weight: 700;
  letter-spacing: -.02em;
  color: var(--text);
}
.rm-label.active .rm-title   { color: var(--green); }
.rm-label.planned .rm-title  { color: var(--orange); }
.rm-label.launched .rm-title { color: var(--blue); }

.rm-cards { display: flex; flex-direction: column; gap: 10px; }

.rm-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 16px 18px;
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
  transition: border-color .2s;
}
.rm-card:hover { border-color: #2e2e44; }

.rm-card-body { flex: 1; min-width: 0; }
.rm-card-title { font-size: 14px; font-weight: 600; color: var(--text); margin-bottom: 4px; }
.rm-card-desc  { font-size: 13px; color: var(--muted); line-height: 1.55; }

.rm-card-meta {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 6px;
  flex-shrink: 0;
}
.rm-tag {
  font-size: 11px;
  font-weight: 500;
  letter-spacing: .04em;
  color: var(--muted);
  background: rgba(255,255,255,.05);
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 2px 8px;
}

.rm-empty {
  background: var(--surface);
  border: 1px dashed var(--border);
  border-radius: 10px;
  padding: 32px 24px;
  text-align: center;
  color: var(--muted);
  font-size: 13px;
  line-height: 1.6;
}

@media (max-width: 540px) {
  .rm-section { grid-template-columns: 1fr; gap: 20px 0; }
  .rm-label { flex-direction: row; align-items: center; }
}
"""


def render_roadmap_card(card: RoadmapCard) -> str:
    title_html = render_inline(card.title)
    desc_html = render_inline(card.description)
    meta_html = ""
    if card.tag:
        meta_html = (
            f'      <div class="rm-card-meta">'
            f'<span class="rm-tag">{html.escape(card.tag)}</span>'
            f'</div>'
        )
    parts = [
        '    <div class="rm-card">',
        '      <div class="rm-card-body">',
        f'        <div class="rm-card-title">{title_html}</div>',
        f'        <div class="rm-card-desc">{desc_html}</div>',
        '      </div>',
    ]
    if meta_html:
        parts.append(meta_html)
    parts.append('    </div>')
    return "\n".join(parts)


def render_roadmap_section(section: RoadmapSection) -> str:
    parts: list[str] = []
    parts.append('<div class="rm-section">')
    parts.append(f'  <div class="rm-label {section.kind}">')
    parts.append(f'    <span class="rm-icon">{html.escape(section.icon)}</span>')
    parts.append(f'    <span class="rm-title">{html.escape(section.title)}</span>')
    parts.append('  </div>')
    parts.append('  <div class="rm-cards">')
    if section.cards:
        for card in section.cards:
            parts.append(render_roadmap_card(card))
    elif section.empty_text:
        parts.append(
            f'    <div class="rm-empty">{render_inline(section.empty_text)}</div>'
        )
    parts.append('  </div>')
    parts.append('</div>')
    return "\n".join(parts)


def render_roadmap_content(subtitle: str, sections: list[RoadmapSection]) -> str:
    parts: list[str] = []
    parts.append('<div class="page-header">')
    parts.append('  <h1>Roadmap</h1>')
    if subtitle:
        parts.append(f'  <p>{render_inline(subtitle)}</p>')
    parts.append('</div>')
    for section in sections:
        parts.append(render_roadmap_section(section))
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Build entry points
# ---------------------------------------------------------------------------

def build_changelog() -> None:
    md = CHANGELOG_MD.read_text(encoding="utf-8")
    releases = parse_changelog(md)
    if not releases:
        print(f"warning: no releases parsed from {CHANGELOG_MD}", file=sys.stderr)
    content = render_changelog_content(releases)
    rendered = render_template(
        title="Changelog — mach",
        page_style=CHANGELOG_CSS,
        active_href="changelog.html",
        content=content,
    )
    output = GENERATED_BANNER + "\n" + rendered
    CHANGELOG_OUT.write_text(output, encoding="utf-8")
    print(f"wrote {CHANGELOG_OUT.relative_to(REPO_ROOT)} ({len(releases)} releases)")


def build_roadmap() -> None:
    md = ROADMAP_MD.read_text(encoding="utf-8")
    subtitle, sections = parse_roadmap(md)
    content = render_roadmap_content(subtitle, sections)
    rendered = render_template(
        title="Roadmap — mach",
        page_style=ROADMAP_CSS,
        active_href="roadmap.html",
        content=content,
    )
    output = GENERATED_BANNER + "\n" + rendered
    ROADMAP_OUT.write_text(output, encoding="utf-8")
    card_count = sum(len(s.cards) for s in sections)
    print(
        f"wrote {ROADMAP_OUT.relative_to(REPO_ROOT)} "
        f"({len(sections)} sections, {card_count} cards)"
    )


def main() -> int:
    if not TEMPLATE_PATH.is_file():
        print(f"error: template not found at {TEMPLATE_PATH}", file=sys.stderr)
        return 1
    if not CHANGELOG_MD.is_file():
        print(f"error: changelog not found at {CHANGELOG_MD}", file=sys.stderr)
        return 1
    if not ROADMAP_MD.is_file():
        print(f"error: roadmap not found at {ROADMAP_MD}", file=sys.stderr)
        return 1

    build_changelog()
    build_roadmap()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
